# Generated by Django 6.0.5 on 2026-05-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movielens_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('plot', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('popularity', models.IntegerField(default=0)),
                ('genres', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('source_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities', to='recommender.movie')),
                ('target_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='recommender.movie')),
            ],
        ),
    ]
